stages:
  - code_audit
  - build
  - audit
  - test

variables:
  # Can be overriden in project/group CI/CD settings
  # BASE_REGISTRY: "artifactory.icz.icdc.io/icdc-docker-proxy"
  # CI_REGISTRY: "artifactory.icz.icdc.io/sys-docker"
  # GITLEAKS_IMAGE: "ghcr.io/gitleaks/gitleaks:latest"
  # SERVICE_GROUP: storage
  IMAGE_NAME: "$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA"
  FULL_IMAGE_NAME: "$CI_REGISTRY/$SERVICE_GROUP/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
    - if: $CI_COMMIT_BRANCH == "dev"

gitleaks:
  stage: code_audit
  tags:
    - testing
  variables:
    CONTAINER_NAME: "${CI_PROJECT_NAME}-gitleaks"
  before_script:
    - mkdir -p output
  script:
    - >
      podman run --rm
      -v "$(pwd):/repo:Z" -w /repo
      --name "${CONTAINER_NAME}"
      "$GITLEAKS_IMAGE" detect
      --redact
      --no-banner
      --source=/repo
      --report-format json
      --report-path /repo/output/gitleaks.json
  artifacts:
    when: always
    paths: [output/gitleaks.json]
    reports:
      secret_detection: output/gitleaks.json
  after_script:
    - podman stop "${CONTAINER_NAME}" || true

build:
  stage: build
  tags:
    - testing
  before_script:
    - podman login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - echo "Building the project... $IMAGE_NAME"
    - podman build --build-arg BASE_REGISTRY=${BASE_REGISTRY} -t "$IMAGE_NAME" .
    - echo "Pushing the image to the registry... $FULL_IMAGE_NAME"
    - podman tag "$IMAGE_NAME" "$FULL_IMAGE_NAME"
    - podman push "$FULL_IMAGE_NAME"

audit:
  stage: audit
  tags:
    - testing
  variables:
    CONTAINER_NAME: "${CI_PROJECT_NAME}-pip-audit"
  before_script:
    - mkdir -p output
  script:
    - echo "Running pip-audit... "
    - >
      podman run --rm
      --name "${CONTAINER_NAME}"
      --entrypoint /bin/sh
      -v "$(pwd)/output:/output:Z"
      "$FULL_IMAGE_NAME" -lc '
        set -e
        pip install -q pip-audit
        IGNORE_ARGS="$(sed "s/^/--ignore-vuln /" .pip-audit.ignore 2>/dev/null || true)"
        pip-audit --progress-spinner off $IGNORE_ARGS -o /output/pip_audit.txt
      '
  after_script:
    - podman stop "${CONTAINER_NAME}" || true
  artifacts:
    when: always
    paths:
      - output/pip_audit.txt
    expire_in: 1 week

tests:
  stage: test
  tags:
    - testing
    - dcz-sys
  variables:
    CONTAINER_NAME: "${CI_PROJECT_NAME}-tests"
  before_script:
    - chmod +x ./run_tests.sh
    - mkdir htmlcov
    - touch report.xml
  script:
    - ./run_tests.sh $FULL_IMAGE_NAME | tee -a result.txt
  after_script:
    - podman stop "${CONTAINER_NAME}" || true
    - podman rmi $(podman images --filter "dangling=true" -q) || true
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)%/'
  artifacts:
    paths:
      - htmlcov
      - result.txt
    expire_in: 1 week
    reports:
      junit: report.xml
