# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from storage.openapi_app.models.base_model_ import Model
from storage.openapi_app import util


class AccountQuota(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, number_of_objects=None, data_size=None, number_of_buckets_per_s3user=None, number_of_s3users=None):  # noqa: E501
        """AccountQuota - a model defined in OpenAPI

        :param number_of_objects: The number_of_objects of this AccountQuota.  # noqa: E501
        :type number_of_objects: long
        :param data_size: The data_size of this AccountQuota.  # noqa: E501
        :type data_size: long
        :param number_of_buckets_per_s3user: The number_of_buckets_per_s3user of this AccountQuota.  # noqa: E501
        :type number_of_buckets_per_s3user: int
        :param number_of_s3users: The number_of_s3users of this AccountQuota.  # noqa: E501
        :type number_of_s3users: long
        """
        self.openapi_types = {
            'number_of_objects': long,
            'data_size': long,
            'number_of_buckets_per_s3user': int,
            'number_of_s3users': long
        }

        self.attribute_map = {
            'number_of_objects': 'number_of_objects',
            'data_size': 'data_size',
            'number_of_buckets_per_s3user': 'number_of_buckets_per_s3user',
            'number_of_s3users': 'number_of_s3users'
        }

        self._number_of_objects = number_of_objects
        self._data_size = data_size
        self._number_of_buckets_per_s3user = number_of_buckets_per_s3user
        self._number_of_s3users = number_of_s3users

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The account_quota of this AccountQuota.  # noqa: E501
        :rtype: AccountQuota
        """
        return util.deserialize_model(dikt, cls)

    @property
    def number_of_objects(self):
        """Gets the number_of_objects of this AccountQuota.

        Number of objects  # noqa: E501

        :return: The number_of_objects of this AccountQuota.
        :rtype: long
        """
        return self._number_of_objects

    @number_of_objects.setter
    def number_of_objects(self, number_of_objects):
        """Sets the number_of_objects of this AccountQuota.

        Number of objects  # noqa: E501

        :param number_of_objects: The number_of_objects of this AccountQuota.
        :type number_of_objects: long
        """
        if number_of_objects is None:
            raise ValueError("Invalid value for `number_of_objects`, must not be `None`")  # noqa: E501

        self._number_of_objects = number_of_objects

    @property
    def data_size(self):
        """Gets the data_size of this AccountQuota.

        data size in bytes  # noqa: E501

        :return: The data_size of this AccountQuota.
        :rtype: long
        """
        return self._data_size

    @data_size.setter
    def data_size(self, data_size):
        """Sets the data_size of this AccountQuota.

        data size in bytes  # noqa: E501

        :param data_size: The data_size of this AccountQuota.
        :type data_size: long
        """
        if data_size is None:
            raise ValueError("Invalid value for `data_size`, must not be `None`")  # noqa: E501

        self._data_size = data_size

    @property
    def number_of_buckets_per_s3user(self):
        """Gets the number_of_buckets_per_s3user of this AccountQuota.


        :return: The number_of_buckets_per_s3user of this AccountQuota.
        :rtype: int
        """
        return self._number_of_buckets_per_s3user

    @number_of_buckets_per_s3user.setter
    def number_of_buckets_per_s3user(self, number_of_buckets_per_s3user):
        """Sets the number_of_buckets_per_s3user of this AccountQuota.


        :param number_of_buckets_per_s3user: The number_of_buckets_per_s3user of this AccountQuota.
        :type number_of_buckets_per_s3user: int
        """

        self._number_of_buckets_per_s3user = number_of_buckets_per_s3user

    @property
    def number_of_s3users(self):
        """Gets the number_of_s3users of this AccountQuota.


        :return: The number_of_s3users of this AccountQuota.
        :rtype: long
        """
        return self._number_of_s3users

    @number_of_s3users.setter
    def number_of_s3users(self, number_of_s3users):
        """Sets the number_of_s3users of this AccountQuota.


        :param number_of_s3users: The number_of_s3users of this AccountQuota.
        :type number_of_s3users: long
        """
        if number_of_s3users is None:
            raise ValueError("Invalid value for `number_of_s3users`, must not be `None`")  # noqa: E501

        self._number_of_s3users = number_of_s3users
