# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from storage.openapi_app.models.base_model_ import Model
from storage.openapi_app.models.account_quota import AccountQuota
from storage.openapi_app import util

from storage.openapi_app.models.account_quota import AccountQuota  # noqa: E501

class AccountMemberQuotaInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, account=None, account_member=None, account_member_quota=None, number_of_created_s3users=None):  # noqa: E501
        """AccountMemberQuotaInfo - a model defined in OpenAPI

        :param account: The account of this AccountMemberQuotaInfo.  # noqa: E501
        :type account: str
        :param account_member: The account_member of this AccountMemberQuotaInfo.  # noqa: E501
        :type account_member: str
        :param account_member_quota: The account_member_quota of this AccountMemberQuotaInfo.  # noqa: E501
        :type account_member_quota: AccountQuota
        :param number_of_created_s3users: The number_of_created_s3users of this AccountMemberQuotaInfo.  # noqa: E501
        :type number_of_created_s3users: int
        """
        self.openapi_types = {
            'account': str,
            'account_member': str,
            'account_member_quota': AccountQuota,
            'number_of_created_s3users': int
        }

        self.attribute_map = {
            'account': 'account',
            'account_member': 'account_member',
            'account_member_quota': 'account_member_quota',
            'number_of_created_s3users': 'number_of_created_s3users'
        }

        self._account = account
        self._account_member = account_member
        self._account_member_quota = account_member_quota
        self._number_of_created_s3users = number_of_created_s3users

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The account_member_quota_info of this AccountMemberQuotaInfo.  # noqa: E501
        :rtype: AccountMemberQuotaInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account(self):
        """Gets the account of this AccountMemberQuotaInfo.


        :return: The account of this AccountMemberQuotaInfo.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this AccountMemberQuotaInfo.


        :param account: The account of this AccountMemberQuotaInfo.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def account_member(self):
        """Gets the account_member of this AccountMemberQuotaInfo.


        :return: The account_member of this AccountMemberQuotaInfo.
        :rtype: str
        """
        return self._account_member

    @account_member.setter
    def account_member(self, account_member):
        """Sets the account_member of this AccountMemberQuotaInfo.


        :param account_member: The account_member of this AccountMemberQuotaInfo.
        :type account_member: str
        """
        if account_member is None:
            raise ValueError("Invalid value for `account_member`, must not be `None`")  # noqa: E501

        self._account_member = account_member

    @property
    def account_member_quota(self):
        """Gets the account_member_quota of this AccountMemberQuotaInfo.


        :return: The account_member_quota of this AccountMemberQuotaInfo.
        :rtype: AccountQuota
        """
        return self._account_member_quota

    @account_member_quota.setter
    def account_member_quota(self, account_member_quota):
        """Sets the account_member_quota of this AccountMemberQuotaInfo.


        :param account_member_quota: The account_member_quota of this AccountMemberQuotaInfo.
        :type account_member_quota: AccountQuota
        """
        if account_member_quota is None:
            raise ValueError("Invalid value for `account_member_quota`, must not be `None`")  # noqa: E501

        self._account_member_quota = account_member_quota

    @property
    def number_of_created_s3users(self):
        """Gets the number_of_created_s3users of this AccountMemberQuotaInfo.


        :return: The number_of_created_s3users of this AccountMemberQuotaInfo.
        :rtype: int
        """
        return self._number_of_created_s3users

    @number_of_created_s3users.setter
    def number_of_created_s3users(self, number_of_created_s3users):
        """Sets the number_of_created_s3users of this AccountMemberQuotaInfo.


        :param number_of_created_s3users: The number_of_created_s3users of this AccountMemberQuotaInfo.
        :type number_of_created_s3users: int
        """
        if number_of_created_s3users is None:
            raise ValueError("Invalid value for `number_of_created_s3users`, must not be `None`")  # noqa: E501

        self._number_of_created_s3users = number_of_created_s3users
