# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from storage.openapi_app.models.base_model_ import Model
from storage.openapi_app.models.storage_quota_or_usage import StorageQuotaOrUsage
from storage.openapi_app import util

from storage.openapi_app.models.storage_quota_or_usage import StorageQuotaOrUsage  # noqa: E501

class BucketCreateOrUpdateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, s3user_name=None, bucket_name=None, quota=None, bucket_properties=None):  # noqa: E501
        """BucketCreateOrUpdateRequest - a model defined in OpenAPI

        :param s3user_name: The s3user_name of this BucketCreateOrUpdateRequest.  # noqa: E501
        :type s3user_name: str
        :param bucket_name: The bucket_name of this BucketCreateOrUpdateRequest.  # noqa: E501
        :type bucket_name: str
        :param quota: The quota of this BucketCreateOrUpdateRequest.  # noqa: E501
        :type quota: StorageQuotaOrUsage
        :param bucket_properties: The bucket_properties of this BucketCreateOrUpdateRequest.  # noqa: E501
        :type bucket_properties: object
        """
        self.openapi_types = {
            's3user_name': str,
            'bucket_name': str,
            'quota': StorageQuotaOrUsage,
            'bucket_properties': object
        }

        self.attribute_map = {
            's3user_name': 's3user_name',
            'bucket_name': 'bucket_name',
            'quota': 'quota',
            'bucket_properties': 'bucket_properties'
        }

        self._s3user_name = s3user_name
        self._bucket_name = bucket_name
        self._quota = quota
        self._bucket_properties = bucket_properties

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The bucket_create_or_update_request of this BucketCreateOrUpdateRequest.  # noqa: E501
        :rtype: BucketCreateOrUpdateRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def s3user_name(self):
        """Gets the s3user_name of this BucketCreateOrUpdateRequest.


        :return: The s3user_name of this BucketCreateOrUpdateRequest.
        :rtype: str
        """
        return self._s3user_name

    @s3user_name.setter
    def s3user_name(self, s3user_name):
        """Sets the s3user_name of this BucketCreateOrUpdateRequest.


        :param s3user_name: The s3user_name of this BucketCreateOrUpdateRequest.
        :type s3user_name: str
        """
        if s3user_name is None:
            raise ValueError("Invalid value for `s3user_name`, must not be `None`")  # noqa: E501

        self._s3user_name = s3user_name

    @property
    def bucket_name(self):
        """Gets the bucket_name of this BucketCreateOrUpdateRequest.


        :return: The bucket_name of this BucketCreateOrUpdateRequest.
        :rtype: str
        """
        return self._bucket_name

    @bucket_name.setter
    def bucket_name(self, bucket_name):
        """Sets the bucket_name of this BucketCreateOrUpdateRequest.


        :param bucket_name: The bucket_name of this BucketCreateOrUpdateRequest.
        :type bucket_name: str
        """
        if bucket_name is None:
            raise ValueError("Invalid value for `bucket_name`, must not be `None`")  # noqa: E501

        self._bucket_name = bucket_name

    @property
    def quota(self):
        """Gets the quota of this BucketCreateOrUpdateRequest.


        :return: The quota of this BucketCreateOrUpdateRequest.
        :rtype: StorageQuotaOrUsage
        """
        return self._quota

    @quota.setter
    def quota(self, quota):
        """Sets the quota of this BucketCreateOrUpdateRequest.


        :param quota: The quota of this BucketCreateOrUpdateRequest.
        :type quota: StorageQuotaOrUsage
        """

        self._quota = quota

    @property
    def bucket_properties(self):
        """Gets the bucket_properties of this BucketCreateOrUpdateRequest.


        :return: The bucket_properties of this BucketCreateOrUpdateRequest.
        :rtype: object
        """
        return self._bucket_properties

    @bucket_properties.setter
    def bucket_properties(self, bucket_properties):
        """Sets the bucket_properties of this BucketCreateOrUpdateRequest.


        :param bucket_properties: The bucket_properties of this BucketCreateOrUpdateRequest.
        :type bucket_properties: object
        """

        self._bucket_properties = bucket_properties
