# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from storage.openapi_app.models.base_model_ import Model
from storage.openapi_app import util


class Error4xx(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bad_item=None, explanation=None):  # noqa: E501
        """Error4xx - a model defined in OpenAPI

        :param bad_item: The bad_item of this Error4xx.  # noqa: E501
        :type bad_item: str
        :param explanation: The explanation of this Error4xx.  # noqa: E501
        :type explanation: str
        """
        self.openapi_types = {
            'bad_item': str,
            'explanation': str
        }

        self.attribute_map = {
            'bad_item': 'bad_item',
            'explanation': 'explanation'
        }

        self._bad_item = bad_item
        self._explanation = explanation

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error4xx of this Error4xx.  # noqa: E501
        :rtype: Error4xx
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bad_item(self):
        """Gets the bad_item of this Error4xx.


        :return: The bad_item of this Error4xx.
        :rtype: str
        """
        return self._bad_item

    @bad_item.setter
    def bad_item(self, bad_item):
        """Sets the bad_item of this Error4xx.


        :param bad_item: The bad_item of this Error4xx.
        :type bad_item: str
        """
        if bad_item is None:
            raise ValueError("Invalid value for `bad_item`, must not be `None`")  # noqa: E501

        self._bad_item = bad_item

    @property
    def explanation(self):
        """Gets the explanation of this Error4xx.


        :return: The explanation of this Error4xx.
        :rtype: str
        """
        return self._explanation

    @explanation.setter
    def explanation(self, explanation):
        """Sets the explanation of this Error4xx.


        :param explanation: The explanation of this Error4xx.
        :type explanation: str
        """
        if explanation is None:
            raise ValueError("Invalid value for `explanation`, must not be `None`")  # noqa: E501

        self._explanation = explanation
