# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from storage.openapi_app.models.base_model_ import Model
from storage.openapi_app.models.account_quota import AccountQuota
from storage.openapi_app.models.storage_quota_or_usage import StorageQuotaOrUsage
from storage.openapi_app import util

from storage.openapi_app.models.account_quota import AccountQuota  # noqa: E501
from storage.openapi_app.models.storage_quota_or_usage import StorageQuotaOrUsage  # noqa: E501

class S3AccountInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, account=None, account_total_quota=None, member_quota=None, current_number_of_s3users=None, actual_storage_usage=None):  # noqa: E501
        """S3AccountInfo - a model defined in OpenAPI

        :param account: The account of this S3AccountInfo.  # noqa: E501
        :type account: str
        :param account_total_quota: The account_total_quota of this S3AccountInfo.  # noqa: E501
        :type account_total_quota: AccountQuota
        :param member_quota: The member_quota of this S3AccountInfo.  # noqa: E501
        :type member_quota: AccountQuota
        :param current_number_of_s3users: The current_number_of_s3users of this S3AccountInfo.  # noqa: E501
        :type current_number_of_s3users: long
        :param actual_storage_usage: The actual_storage_usage of this S3AccountInfo.  # noqa: E501
        :type actual_storage_usage: StorageQuotaOrUsage
        """
        self.openapi_types = {
            'account': str,
            'account_total_quota': AccountQuota,
            'member_quota': AccountQuota,
            'current_number_of_s3users': long,
            'actual_storage_usage': StorageQuotaOrUsage
        }

        self.attribute_map = {
            'account': 'account',
            'account_total_quota': 'account_total_quota',
            'member_quota': 'member_quota',
            'current_number_of_s3users': 'current_number_of_s3users',
            'actual_storage_usage': 'actual_storage_usage'
        }

        self._account = account
        self._account_total_quota = account_total_quota
        self._member_quota = member_quota
        self._current_number_of_s3users = current_number_of_s3users
        self._actual_storage_usage = actual_storage_usage

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The s3_account_info of this S3AccountInfo.  # noqa: E501
        :rtype: S3AccountInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account(self):
        """Gets the account of this S3AccountInfo.


        :return: The account of this S3AccountInfo.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this S3AccountInfo.


        :param account: The account of this S3AccountInfo.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def account_total_quota(self):
        """Gets the account_total_quota of this S3AccountInfo.


        :return: The account_total_quota of this S3AccountInfo.
        :rtype: AccountQuota
        """
        return self._account_total_quota

    @account_total_quota.setter
    def account_total_quota(self, account_total_quota):
        """Sets the account_total_quota of this S3AccountInfo.


        :param account_total_quota: The account_total_quota of this S3AccountInfo.
        :type account_total_quota: AccountQuota
        """
        if account_total_quota is None:
            raise ValueError("Invalid value for `account_total_quota`, must not be `None`")  # noqa: E501

        self._account_total_quota = account_total_quota

    @property
    def member_quota(self):
        """Gets the member_quota of this S3AccountInfo.


        :return: The member_quota of this S3AccountInfo.
        :rtype: AccountQuota
        """
        return self._member_quota

    @member_quota.setter
    def member_quota(self, member_quota):
        """Sets the member_quota of this S3AccountInfo.


        :param member_quota: The member_quota of this S3AccountInfo.
        :type member_quota: AccountQuota
        """
        if member_quota is None:
            raise ValueError("Invalid value for `member_quota`, must not be `None`")  # noqa: E501

        self._member_quota = member_quota

    @property
    def current_number_of_s3users(self):
        """Gets the current_number_of_s3users of this S3AccountInfo.


        :return: The current_number_of_s3users of this S3AccountInfo.
        :rtype: long
        """
        return self._current_number_of_s3users

    @current_number_of_s3users.setter
    def current_number_of_s3users(self, current_number_of_s3users):
        """Sets the current_number_of_s3users of this S3AccountInfo.


        :param current_number_of_s3users: The current_number_of_s3users of this S3AccountInfo.
        :type current_number_of_s3users: long
        """
        if current_number_of_s3users is None:
            raise ValueError("Invalid value for `current_number_of_s3users`, must not be `None`")  # noqa: E501

        self._current_number_of_s3users = current_number_of_s3users

    @property
    def actual_storage_usage(self):
        """Gets the actual_storage_usage of this S3AccountInfo.


        :return: The actual_storage_usage of this S3AccountInfo.
        :rtype: StorageQuotaOrUsage
        """
        return self._actual_storage_usage

    @actual_storage_usage.setter
    def actual_storage_usage(self, actual_storage_usage):
        """Sets the actual_storage_usage of this S3AccountInfo.


        :param actual_storage_usage: The actual_storage_usage of this S3AccountInfo.
        :type actual_storage_usage: StorageQuotaOrUsage
        """

        self._actual_storage_usage = actual_storage_usage
