# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from storage.openapi_app.models.base_model_ import Model
from storage.openapi_app.models.s3user_quota_or_usage import S3userQuotaOrUsage
from storage.openapi_app.models.storage_quota_or_usage import StorageQuotaOrUsage
from storage.openapi_app import util

from storage.openapi_app.models.s3user_quota_or_usage import S3userQuotaOrUsage  # noqa: E501
from storage.openapi_app.models.storage_quota_or_usage import StorageQuotaOrUsage  # noqa: E501

class S3user(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, account=None, owner=None, s3user_name=None, s3user_description=None, secret_key=None, access_key=None, swift_id=None, swift_key=None, default_quota_per_bucket=None, quota_per_s3user=None, current_actual_usage=None):  # noqa: E501
        """S3user - a model defined in OpenAPI

        :param account: The account of this S3user.  # noqa: E501
        :type account: str
        :param owner: The owner of this S3user.  # noqa: E501
        :type owner: str
        :param s3user_name: The s3user_name of this S3user.  # noqa: E501
        :type s3user_name: str
        :param s3user_description: The s3user_description of this S3user.  # noqa: E501
        :type s3user_description: str
        :param secret_key: The secret_key of this S3user.  # noqa: E501
        :type secret_key: str
        :param access_key: The access_key of this S3user.  # noqa: E501
        :type access_key: str
        :param swift_id: The swift_id of this S3user.  # noqa: E501
        :type swift_id: str
        :param swift_key: The swift_key of this S3user.  # noqa: E501
        :type swift_key: str
        :param default_quota_per_bucket: The default_quota_per_bucket of this S3user.  # noqa: E501
        :type default_quota_per_bucket: StorageQuotaOrUsage
        :param quota_per_s3user: The quota_per_s3user of this S3user.  # noqa: E501
        :type quota_per_s3user: S3userQuotaOrUsage
        :param current_actual_usage: The current_actual_usage of this S3user.  # noqa: E501
        :type current_actual_usage: S3userQuotaOrUsage
        """
        self.openapi_types = {
            'account': str,
            'owner': str,
            's3user_name': str,
            's3user_description': str,
            'secret_key': str,
            'access_key': str,
            'swift_id': str,
            'swift_key': str,
            'default_quota_per_bucket': StorageQuotaOrUsage,
            'quota_per_s3user': S3userQuotaOrUsage,
            'current_actual_usage': S3userQuotaOrUsage
        }

        self.attribute_map = {
            'account': 'account',
            'owner': 'owner',
            's3user_name': 's3user_name',
            's3user_description': 's3user_description',
            'secret_key': 'secret_key',
            'access_key': 'access_key',
            'swift_id': 'swift_id',
            'swift_key': 'swift_key',
            'default_quota_per_bucket': 'default_quota_per_bucket',
            'quota_per_s3user': 'quota_per_s3user',
            'current_actual_usage': 'current_actual_usage'
        }

        self._account = account
        self._owner = owner
        self._s3user_name = s3user_name
        self._s3user_description = s3user_description
        self._secret_key = secret_key
        self._access_key = access_key
        self._swift_id = swift_id
        self._swift_key = swift_key
        self._default_quota_per_bucket = default_quota_per_bucket
        self._quota_per_s3user = quota_per_s3user
        self._current_actual_usage = current_actual_usage

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The s3user of this S3user.  # noqa: E501
        :rtype: S3user
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account(self):
        """Gets the account of this S3user.


        :return: The account of this S3user.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this S3user.


        :param account: The account of this S3user.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def owner(self):
        """Gets the owner of this S3user.

        Name of the account member, who owns the s3user. If emty then s3user will be visible only for  account admins  # noqa: E501

        :return: The owner of this S3user.
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this S3user.

        Name of the account member, who owns the s3user. If emty then s3user will be visible only for  account admins  # noqa: E501

        :param owner: The owner of this S3user.
        :type owner: str
        """

        self._owner = owner

    @property
    def s3user_name(self):
        """Gets the s3user_name of this S3user.


        :return: The s3user_name of this S3user.
        :rtype: str
        """
        return self._s3user_name

    @s3user_name.setter
    def s3user_name(self, s3user_name):
        """Sets the s3user_name of this S3user.


        :param s3user_name: The s3user_name of this S3user.
        :type s3user_name: str
        """
        if s3user_name is None:
            raise ValueError("Invalid value for `s3user_name`, must not be `None`")  # noqa: E501

        self._s3user_name = s3user_name

    @property
    def s3user_description(self):
        """Gets the s3user_description of this S3user.


        :return: The s3user_description of this S3user.
        :rtype: str
        """
        return self._s3user_description

    @s3user_description.setter
    def s3user_description(self, s3user_description):
        """Sets the s3user_description of this S3user.


        :param s3user_description: The s3user_description of this S3user.
        :type s3user_description: str
        """
        if s3user_description is None:
            raise ValueError("Invalid value for `s3user_description`, must not be `None`")  # noqa: E501

        self._s3user_description = s3user_description

    @property
    def secret_key(self):
        """Gets the secret_key of this S3user.


        :return: The secret_key of this S3user.
        :rtype: str
        """
        return self._secret_key

    @secret_key.setter
    def secret_key(self, secret_key):
        """Sets the secret_key of this S3user.


        :param secret_key: The secret_key of this S3user.
        :type secret_key: str
        """
        if secret_key is None:
            raise ValueError("Invalid value for `secret_key`, must not be `None`")  # noqa: E501

        self._secret_key = secret_key

    @property
    def access_key(self):
        """Gets the access_key of this S3user.


        :return: The access_key of this S3user.
        :rtype: str
        """
        return self._access_key

    @access_key.setter
    def access_key(self, access_key):
        """Sets the access_key of this S3user.


        :param access_key: The access_key of this S3user.
        :type access_key: str
        """
        if access_key is None:
            raise ValueError("Invalid value for `access_key`, must not be `None`")  # noqa: E501

        self._access_key = access_key

    @property
    def swift_id(self):
        """Gets the swift_id of this S3user.


        :return: The swift_id of this S3user.
        :rtype: str
        """
        return self._swift_id

    @swift_id.setter
    def swift_id(self, swift_id):
        """Sets the swift_id of this S3user.


        :param swift_id: The swift_id of this S3user.
        :type swift_id: str
        """
        if swift_id is None:
            raise ValueError("Invalid value for `swift_id`, must not be `None`")  # noqa: E501

        self._swift_id = swift_id

    @property
    def swift_key(self):
        """Gets the swift_key of this S3user.


        :return: The swift_key of this S3user.
        :rtype: str
        """
        return self._swift_key

    @swift_key.setter
    def swift_key(self, swift_key):
        """Sets the swift_key of this S3user.


        :param swift_key: The swift_key of this S3user.
        :type swift_key: str
        """
        if swift_key is None:
            raise ValueError("Invalid value for `swift_key`, must not be `None`")  # noqa: E501

        self._swift_key = swift_key

    @property
    def default_quota_per_bucket(self):
        """Gets the default_quota_per_bucket of this S3user.


        :return: The default_quota_per_bucket of this S3user.
        :rtype: StorageQuotaOrUsage
        """
        return self._default_quota_per_bucket

    @default_quota_per_bucket.setter
    def default_quota_per_bucket(self, default_quota_per_bucket):
        """Sets the default_quota_per_bucket of this S3user.


        :param default_quota_per_bucket: The default_quota_per_bucket of this S3user.
        :type default_quota_per_bucket: StorageQuotaOrUsage
        """
        if default_quota_per_bucket is None:
            raise ValueError("Invalid value for `default_quota_per_bucket`, must not be `None`")  # noqa: E501

        self._default_quota_per_bucket = default_quota_per_bucket

    @property
    def quota_per_s3user(self):
        """Gets the quota_per_s3user of this S3user.


        :return: The quota_per_s3user of this S3user.
        :rtype: S3userQuotaOrUsage
        """
        return self._quota_per_s3user

    @quota_per_s3user.setter
    def quota_per_s3user(self, quota_per_s3user):
        """Sets the quota_per_s3user of this S3user.


        :param quota_per_s3user: The quota_per_s3user of this S3user.
        :type quota_per_s3user: S3userQuotaOrUsage
        """
        if quota_per_s3user is None:
            raise ValueError("Invalid value for `quota_per_s3user`, must not be `None`")  # noqa: E501

        self._quota_per_s3user = quota_per_s3user

    @property
    def current_actual_usage(self):
        """Gets the current_actual_usage of this S3user.


        :return: The current_actual_usage of this S3user.
        :rtype: S3userQuotaOrUsage
        """
        return self._current_actual_usage

    @current_actual_usage.setter
    def current_actual_usage(self, current_actual_usage):
        """Sets the current_actual_usage of this S3user.


        :param current_actual_usage: The current_actual_usage of this S3user.
        :type current_actual_usage: S3userQuotaOrUsage
        """
        if current_actual_usage is None:
            raise ValueError("Invalid value for `current_actual_usage`, must not be `None`")  # noqa: E501

        self._current_actual_usage = current_actual_usage
