# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from storage.openapi_app.models.base_model_ import Model
from storage.openapi_app.models.s3user_quota_or_usage import S3userQuotaOrUsage
from storage.openapi_app.models.storage_quota_or_usage import StorageQuotaOrUsage
from storage.openapi_app import util

from storage.openapi_app.models.s3user_quota_or_usage import S3userQuotaOrUsage  # noqa: E501
from storage.openapi_app.models.storage_quota_or_usage import StorageQuotaOrUsage  # noqa: E501

class S3userCreateOrUpdateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, account=None, owner=None, s3user_name=None, s3user_description=None, quota_per_s3user=None, default_quota_per_bucket=None):  # noqa: E501
        """S3userCreateOrUpdateRequest - a model defined in OpenAPI

        :param account: The account of this S3userCreateOrUpdateRequest.  # noqa: E501
        :type account: str
        :param owner: The owner of this S3userCreateOrUpdateRequest.  # noqa: E501
        :type owner: str
        :param s3user_name: The s3user_name of this S3userCreateOrUpdateRequest.  # noqa: E501
        :type s3user_name: str
        :param s3user_description: The s3user_description of this S3userCreateOrUpdateRequest.  # noqa: E501
        :type s3user_description: str
        :param quota_per_s3user: The quota_per_s3user of this S3userCreateOrUpdateRequest.  # noqa: E501
        :type quota_per_s3user: S3userQuotaOrUsage
        :param default_quota_per_bucket: The default_quota_per_bucket of this S3userCreateOrUpdateRequest.  # noqa: E501
        :type default_quota_per_bucket: StorageQuotaOrUsage
        """
        self.openapi_types = {
            'account': str,
            'owner': str,
            's3user_name': str,
            's3user_description': str,
            'quota_per_s3user': S3userQuotaOrUsage,
            'default_quota_per_bucket': StorageQuotaOrUsage
        }

        self.attribute_map = {
            'account': 'account',
            'owner': 'owner',
            's3user_name': 's3user_name',
            's3user_description': 's3user_description',
            'quota_per_s3user': 'quota_per_s3user',
            'default_quota_per_bucket': 'default_quota_per_bucket'
        }

        self._account = account
        self._owner = owner
        self._s3user_name = s3user_name
        self._s3user_description = s3user_description
        self._quota_per_s3user = quota_per_s3user
        self._default_quota_per_bucket = default_quota_per_bucket

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The s3user_create_or_update_request of this S3userCreateOrUpdateRequest.  # noqa: E501
        :rtype: S3userCreateOrUpdateRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account(self):
        """Gets the account of this S3userCreateOrUpdateRequest.

        Account in which user is created. The field is immutable after creation  # noqa: E501

        :return: The account of this S3userCreateOrUpdateRequest.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this S3userCreateOrUpdateRequest.

        Account in which user is created. The field is immutable after creation  # noqa: E501

        :param account: The account of this S3userCreateOrUpdateRequest.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def owner(self):
        """Gets the owner of this S3userCreateOrUpdateRequest.

        Name of the account member, who will own the s3user. If emty then s3user will be visible only for  account admins  # noqa: E501

        :return: The owner of this S3userCreateOrUpdateRequest.
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this S3userCreateOrUpdateRequest.

        Name of the account member, who will own the s3user. If emty then s3user will be visible only for  account admins  # noqa: E501

        :param owner: The owner of this S3userCreateOrUpdateRequest.
        :type owner: str
        """

        self._owner = owner

    @property
    def s3user_name(self):
        """Gets the s3user_name of this S3userCreateOrUpdateRequest.

        The field is Immutable after creation  # noqa: E501

        :return: The s3user_name of this S3userCreateOrUpdateRequest.
        :rtype: str
        """
        return self._s3user_name

    @s3user_name.setter
    def s3user_name(self, s3user_name):
        """Sets the s3user_name of this S3userCreateOrUpdateRequest.

        The field is Immutable after creation  # noqa: E501

        :param s3user_name: The s3user_name of this S3userCreateOrUpdateRequest.
        :type s3user_name: str
        """
        if s3user_name is None:
            raise ValueError("Invalid value for `s3user_name`, must not be `None`")  # noqa: E501

        self._s3user_name = s3user_name

    @property
    def s3user_description(self):
        """Gets the s3user_description of this S3userCreateOrUpdateRequest.


        :return: The s3user_description of this S3userCreateOrUpdateRequest.
        :rtype: str
        """
        return self._s3user_description

    @s3user_description.setter
    def s3user_description(self, s3user_description):
        """Sets the s3user_description of this S3userCreateOrUpdateRequest.


        :param s3user_description: The s3user_description of this S3userCreateOrUpdateRequest.
        :type s3user_description: str
        """
        if s3user_description is None:
            raise ValueError("Invalid value for `s3user_description`, must not be `None`")  # noqa: E501

        self._s3user_description = s3user_description

    @property
    def quota_per_s3user(self):
        """Gets the quota_per_s3user of this S3userCreateOrUpdateRequest.


        :return: The quota_per_s3user of this S3userCreateOrUpdateRequest.
        :rtype: S3userQuotaOrUsage
        """
        return self._quota_per_s3user

    @quota_per_s3user.setter
    def quota_per_s3user(self, quota_per_s3user):
        """Sets the quota_per_s3user of this S3userCreateOrUpdateRequest.


        :param quota_per_s3user: The quota_per_s3user of this S3userCreateOrUpdateRequest.
        :type quota_per_s3user: S3userQuotaOrUsage
        """
        if quota_per_s3user is None:
            raise ValueError("Invalid value for `quota_per_s3user`, must not be `None`")  # noqa: E501

        self._quota_per_s3user = quota_per_s3user

    @property
    def default_quota_per_bucket(self):
        """Gets the default_quota_per_bucket of this S3userCreateOrUpdateRequest.


        :return: The default_quota_per_bucket of this S3userCreateOrUpdateRequest.
        :rtype: StorageQuotaOrUsage
        """
        return self._default_quota_per_bucket

    @default_quota_per_bucket.setter
    def default_quota_per_bucket(self, default_quota_per_bucket):
        """Sets the default_quota_per_bucket of this S3userCreateOrUpdateRequest.


        :param default_quota_per_bucket: The default_quota_per_bucket of this S3userCreateOrUpdateRequest.
        :type default_quota_per_bucket: StorageQuotaOrUsage
        """

        self._default_quota_per_bucket = default_quota_per_bucket
