# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from storage.openapi_app.models.base_model_ import Model
from storage.openapi_app import util


class StorageQuotaOrUsage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, number_of_objects=None, data_size=None):  # noqa: E501
        """StorageQuotaOrUsage - a model defined in OpenAPI

        :param number_of_objects: The number_of_objects of this StorageQuotaOrUsage.  # noqa: E501
        :type number_of_objects: long
        :param data_size: The data_size of this StorageQuotaOrUsage.  # noqa: E501
        :type data_size: long
        """
        self.openapi_types = {
            'number_of_objects': long,
            'data_size': long
        }

        self.attribute_map = {
            'number_of_objects': 'number_of_objects',
            'data_size': 'data_size'
        }

        self._number_of_objects = number_of_objects
        self._data_size = data_size

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The storage_quota_or_usage of this StorageQuotaOrUsage.  # noqa: E501
        :rtype: StorageQuotaOrUsage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def number_of_objects(self):
        """Gets the number_of_objects of this StorageQuotaOrUsage.

        Number of objects  # noqa: E501

        :return: The number_of_objects of this StorageQuotaOrUsage.
        :rtype: long
        """
        return self._number_of_objects

    @number_of_objects.setter
    def number_of_objects(self, number_of_objects):
        """Sets the number_of_objects of this StorageQuotaOrUsage.

        Number of objects  # noqa: E501

        :param number_of_objects: The number_of_objects of this StorageQuotaOrUsage.
        :type number_of_objects: long
        """
        if number_of_objects is None:
            raise ValueError("Invalid value for `number_of_objects`, must not be `None`")  # noqa: E501

        self._number_of_objects = number_of_objects

    @property
    def data_size(self):
        """Gets the data_size of this StorageQuotaOrUsage.

        data size  # noqa: E501

        :return: The data_size of this StorageQuotaOrUsage.
        :rtype: long
        """
        return self._data_size

    @data_size.setter
    def data_size(self, data_size):
        """Sets the data_size of this StorageQuotaOrUsage.

        data size  # noqa: E501

        :param data_size: The data_size of this StorageQuotaOrUsage.
        :type data_size: long
        """
        if data_size is None:
            raise ValueError("Invalid value for `data_size`, must not be `None`")  # noqa: E501

        self._data_size = data_size
