---
log:
  level: DEBUG
location:
  domain: dcz.lab.icdc.io
account:
  default: default
ceph:
  host:  # VIP address of haproxy node
  port: 80 # haproxy on nodes
  max_workers: 10
  prometheus:
    host: "{CEPH_HOST}:9285"
  ssh:
    user: root
    host: "{CEPH_HOST}"
    port: 22
    key: "/.ssh/id_rsa"
  access_key:
  secret_key:
  pool:
    s3:
      nvme:
        limits:
          objects: 100000
          data_size_mb: 178257920
          buckets: 10000
          users: 1000
      ssd:
        limits:
          objects: 100000
          data_size_mb: 178257920
          buckets: 10000
          users: 1000
      hdd:
        limits:
          objects: 100000
          data_size_mb: 178257920
          buckets: 10000
          users: 1000
      hdd-2:
        limits:
          objects: 100000
          data_size_mb: 178257920
          buckets: 10000
          users: 1000
        klass: hdd
    iscsi:
      nvme:
        limits:
          clients: 100
          disks: 50
          data_size_gb: 1500
          snapshots: 100
      ssd:
        limits:
          clients: 100
          disks: 60
          data_size_gb: 1500
          snapshots: 100
      hdd:
        limits:
          clients: 100
          disks: 70
          data_size_gb: 1500
          snapshots: 100
      hdd-2:
        limits:
          clients: 100
          disks: 80
          data_size_gb: 1500
          snapshots: 100
database:
  host:
  port:
  username:
  password:
  name:
operator:
  group: devel.operator
