apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: storage-api
  name: storage-api
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'storage-api:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://git.zby.icdc.io/icdc/storage/storage-api.git'
    sourceSecret:
      name: os-deploy
    type: Git
  strategy:
    dockerStrategy:
      env:
        - name: GIT_AUTH
          valueFrom:
            secretKeyRef:
              key: GIT_CRED
              name: git-cred
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - gitlab:
        secretReference:
          name: storage-api-push-event
      type: GitLab
