apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: storage-api
  name: storage-api
spec:
  replicas: 1
  selector:
    app: storage-api
    deploymentconfig: storage-api
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: storage-api
        deploymentconfig: storage-api
    spec:
      containers:
        - env:
            - name: STORAGE_CONF
              value: /etc/ceph/storage.conf
          image: docker-registry.default.svc:5000/icdc-cloud-stage/storage-api:latest
          imagePullPolicy: Always
          name: storage-api
          ports:
            - containerPort: 8888
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/ceph
              name: ceph-config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: ceph-config
          secret:
            defaultMode: 420
            secretName: storage-api
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - storage-api
        from:
          kind: ImageStreamTag
          name: 'storage-api:latest'
      type: ImageChange
