"""empty message

Revision ID: fc43209701a5
Revises: 
Create Date: 2024-03-25 16:31:47.760867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc43209701a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('s3_placement_target', sa.String(length=128), nullable=True),
    sa.Column('klass', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iscsi_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('chap_username', sa.String(length=128), nullable=True),
    sa.Column('chap_password', sa.String(length=128), nullable=True),
    sa.Column('iqn', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iqn')
    )
    op.create_table('iscsi_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_iqn', sa.String(length=256), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iscsi_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clients', sa.Integer(), nullable=True),
    sa.Column('data_size_gb', sa.Integer(), nullable=True),
    sa.Column('disks', sa.Integer(), nullable=True),
    sa.Column('snapshots', sa.Integer(), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'account_id', name='iscsi_quotas_pool_id_account_id')
    )
    op.create_table('s3_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objects', sa.Integer(), nullable=True),
    sa.Column('data_size_mb', sa.Integer(), nullable=True),
    sa.Column('buckets', sa.Integer(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'account_id', name='s3_quotas_pool_id_account_id')
    )
    op.create_table('s3_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('default_placement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['default_placement'], ['pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iscsi_disks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('size_gb', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['iscsi_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iscsi_gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('portal_ip_address', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=128), nullable=True),
    sa.Column('cloudgw_id', sa.String(length=128), nullable=True),
    sa.Column('api_user', sa.String(length=128), nullable=True),
    sa.Column('api_password', sa.String(length=128), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['iscsi_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iscsi_assigned_clients',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('disk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['iscsi_clients.id'], ),
    sa.ForeignKeyConstraint(['disk_id'], ['iscsi_disks.id'], ),
    info={'bind_key': None}
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('size_gb', sa.Integer(), nullable=True),
    sa.Column('provisioned', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('creation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disk_id'], ['iscsi_disks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots')
    op.drop_table('iscsi_assigned_clients')
    op.drop_table('iscsi_gateways')
    op.drop_table('iscsi_disks')
    op.drop_table('s3_users')
    op.drop_table('s3_quotas')
    op.drop_table('iscsi_quotas')
    op.drop_table('iscsi_configs')
    op.drop_table('iscsi_clients')
    op.drop_table('pools')
    op.drop_table('accounts')
    # ### end Alembic commands ###
