import pytest

from tests.factories.iscsi_targets import IscsiTargetFactory


# Basic target fixtures
@pytest.fixture(scope="function")
def target(cluster, iscsi_quota, iscsi_pools):
    """Create a single iSCSI target for a new autogenerated cluster (uses nvme pool)."""
    return IscsiTargetFactory.create(
        cluster_id=cluster.id,
        pool_id=iscsi_pools["nvme"].id,
    )


@pytest.fixture
def target_factory(cluster_factory, iscsi_quota_factory, iscsi_pools):
    """
    Factory to create one or multiple iSCSI targets.

    Args:
        cluster: Cluster to create targets for (auto-created if omitted)
        quota: Optional quota object (used to align account if cluster not provided)
        target_pools: Single pool name or list of names (default: "nvme")
        create_quota: Whether to auto-create quota for target pools
        **kwargs: Additional params for IscsiTargetFactory

    Returns:
        Single target if one pool, otherwise list of targets.
    """
    def _create_targets(
        cluster=None,
        account=None,
        target_pools="nvme",
        create_quota=False,
        **kwargs
    ):
        # Auto-create cluster
        if cluster is None:
            cluster = cluster_factory(account=account)

        # Auto-create quota for pools if requested
        if create_quota:
            iscsi_quota_factory(cluster.account, quota_pools=target_pools)

        # Normalize pools to list
        pool_names = _normalize_pools(target_pools)

        # Create one target per pool
        targets = [
            IscsiTargetFactory.create(
                cluster_id=cluster.id,
                pool_id=iscsi_pools[p].id,
                **kwargs,
            )
            for p in pool_names
        ]

        return targets[0] if len(targets) == 1 else targets

    def _normalize_pools(pools):
        """Ensure pool names are always represented as a list."""
        if pools is None:
            return ["nvme"]
        return [pools] if isinstance(pools, str) else pools

    return _create_targets


@pytest.fixture
def target_pools(aqa):
    """Retrieve all iSCSI targets for AQA account indexed by pool name.

    Returns:
        dict: Mapping of pool_name -> target object
    """
    return [
        target.pool.name
        for cluster in aqa.iscsi_clusters
        for target in cluster.targets
    ]


def aqa_targets(aqa):
    """Retrieve all iSCSI targets for AQA account indexed by pool name.

    Returns:
        dict: Mapping of pool_name -> target object
    """
    return {
        target.pool.name: target
        for cluster in aqa.iscsi_clusters
        for target in cluster.targets
    }
