import pytest

from tests.factories.iscsi_cluster import IscsiClusterFactory


# Basic cluster fixtures
@pytest.fixture(scope="function")
def cluster(account):
    """Create a single iSCSI cluster for a new autogenerated test account."""
    return IscsiClusterFactory.create(account_id=account.id)


@pytest.fixture
def cluster_factory(account_factory):
    """Factory to create multiple iSCSI clusters.

    Args:
        account: Account to create clusters for. If not provided, a new account
                 will be created automatically.
        count: Number of clusters to create (default: 1)
        **kwargs: Additional parameters to pass to IscsiClusterFactory

    Returns:
        Single cluster if count=1, list of clusters otherwise
    """
    def _create_clusters(account=None, count: int = 1, **kwargs):
        if not account:
            account = account_factory()

        clusters = [
            IscsiClusterFactory.create(account_id=account.id, **kwargs)
            for _ in range(count)
        ]
        return clusters[0] if count == 1 else clusters

    return _create_clusters

