import pytest

from tests.factories.iscsi_gateway import IscsiGatewayFactory


# Basic gateway fixtures
@pytest.fixture(scope="function")
def gateway(cluster_factory):
    """Create a single iSCSI gateway for a new autogenerated cluster."""
    cluster = cluster_factory()
    return IscsiGatewayFactory.create(cluster_id=cluster.id)


@pytest.fixture
def gateway_factory(cluster_factory):
    """Factory to create one or multiple iSCSI gateways.

    Args:
        cluster: Cluster to create gateways for. If omitted, a new cluster
                 will be created automatically.
        count: Number of gateways to create (default: 1)
        **kwargs: Extra parameters for IscsiGatewayFactory

    Returns:
        Single gateway if count=1, otherwise list of gateways.
    """
    def _create_gateways(cluster=None, count: int = 1, **kwargs):
        cluster = cluster or cluster_factory()

        gateways = [
            IscsiGatewayFactory.create(cluster_id=cluster.id, **kwargs)
            for _ in range(count)
        ]
        return gateways[0] if count == 1 else gateways

    return _create_gateways
